<?php
/**
 * BlockParagraph automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BlockParagraph extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?Paragraph $paragraph = null;
    public function setParagraph(?Paragraph $paragraph): void
    {
        $this->paragraph = $paragraph;
    }
    public function getParagraph(): ?Paragraph
    {
        return $this->paragraph;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('paragraph', $this->paragraph);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
