<?php
/**
 * BlockHeading2 automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BlockHeading extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('heading_2')]
    #[Description('')]
    protected ?BlockHeading $heading = null;
    public function setHeading(?BlockHeading $heading): void
    {
        $this->heading = $heading;
    }
    public function getHeading(): ?BlockHeading
    {
        return $this->heading;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('heading_2', $this->heading);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
