<?php
/**
 * BlockBookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BlockBookmark extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?Bookmark $bookmark = null;
    public function setBookmark(?Bookmark $bookmark): void
    {
        $this->bookmark = $bookmark;
    }
    public function getBookmark(): ?Bookmark
    {
        return $this->bookmark;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('bookmark', $this->bookmark);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
