<?php
/**
 * BlockParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BlockParentId extends ParentId implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('block_id')]
    #[Description('')]
    protected ?string $blockId = null;
    public function setBlockId(?string $blockId): void
    {
        $this->blockId = $blockId;
    }
    public function getBlockId(): ?string
    {
        return $this->blockId;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('block_id', $this->blockId);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
