<?php
/**
 * BlockBulletedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BlockBulletedListItem extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('bulleted_list_item')]
    #[Description('')]
    protected ?BulletedListItem $bulletedListItem = null;
    public function setBulletedListItem(?BulletedListItem $bulletedListItem): void
    {
        $this->bulletedListItem = $bulletedListItem;
    }
    public function getBulletedListItem(): ?BulletedListItem
    {
        return $this->bulletedListItem;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('bulleted_list_item', $this->bulletedListItem);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
