<?php
/**
 * BlockPDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BlockPDF extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?PDF $pdf = null;
    public function setPdf(?PDF $pdf): void
    {
        $this->pdf = $pdf;
    }
    public function getPdf(): ?PDF
    {
        return $this->pdf;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('pdf', $this->pdf);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
