<?php
/**
 * Block automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $object = null;
    #[Description('')]
    protected ?string $id = null;
    #[Description('')]
    protected ?Page $parent = null;
    #[Key('created_time')]
    #[Description('')]
    protected ?\PSX\DateTime\LocalDateTime $createdTime = null;
    #[Key('last_edited_time')]
    #[Description('')]
    protected ?\PSX\DateTime\LocalDateTime $lastEditedTime = null;
    #[Key('created_by')]
    #[Description('')]
    protected ?User $createdBy = null;
    #[Key('last_edited_by')]
    #[Description('')]
    protected ?User $lastEditedBy = null;
    #[Key('has_children')]
    #[Description('')]
    protected ?bool $hasChildren = null;
    #[Key('in_trash')]
    #[Description('')]
    protected ?bool $inTrash = null;
    #[Description('')]
    protected ?string $type = null;
    public function setObject(?string $object): void
    {
        $this->object = $object;
    }
    public function getObject(): ?string
    {
        return $this->object;
    }
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setParent(?Page $parent): void
    {
        $this->parent = $parent;
    }
    public function getParent(): ?Page
    {
        return $this->parent;
    }
    public function setCreatedTime(?\PSX\DateTime\LocalDateTime $createdTime): void
    {
        $this->createdTime = $createdTime;
    }
    public function getCreatedTime(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->createdTime;
    }
    public function setLastEditedTime(?\PSX\DateTime\LocalDateTime $lastEditedTime): void
    {
        $this->lastEditedTime = $lastEditedTime;
    }
    public function getLastEditedTime(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->lastEditedTime;
    }
    public function setCreatedBy(?User $createdBy): void
    {
        $this->createdBy = $createdBy;
    }
    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }
    public function setLastEditedBy(?User $lastEditedBy): void
    {
        $this->lastEditedBy = $lastEditedBy;
    }
    public function getLastEditedBy(): ?User
    {
        return $this->lastEditedBy;
    }
    public function setHasChildren(?bool $hasChildren): void
    {
        $this->hasChildren = $hasChildren;
    }
    public function getHasChildren(): ?bool
    {
        return $this->hasChildren;
    }
    public function setInTrash(?bool $inTrash): void
    {
        $this->inTrash = $inTrash;
    }
    public function getInTrash(): ?bool
    {
        return $this->inTrash;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('object', $this->object);
        $record->put('id', $this->id);
        $record->put('parent', $this->parent);
        $record->put('created_time', $this->createdTime);
        $record->put('last_edited_time', $this->lastEditedTime);
        $record->put('created_by', $this->createdBy);
        $record->put('last_edited_by', $this->lastEditedBy);
        $record->put('has_children', $this->hasChildren);
        $record->put('in_trash', $this->inTrash);
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
