<?php
/**
 * BlockBreadcrumb automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BlockBreadcrumb extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
