<?php
/**
 * BlockLinkPreview automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BlockLinkPreview implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('link_preview')]
    #[Description('')]
    protected ?LinkPreview $linkPreview = null;
    public function setLinkPreview(?LinkPreview $linkPreview): void
    {
        $this->linkPreview = $linkPreview;
    }
    public function getLinkPreview(): ?LinkPreview
    {
        return $this->linkPreview;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('link_preview', $this->linkPreview);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
