<?php
/**
 * BlockChildPage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BlockChildPage extends Block implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('child_page')]
    #[Description('')]
    protected ?ChildPage $childPage = null;
    public function setChildPage(?ChildPage $childPage): void
    {
        $this->childPage = $childPage;
    }
    public function getChildPage(): ?ChildPage
    {
        return $this->childPage;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('child_page', $this->childPage);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
