<?php
/**
 * Bookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Bookmark implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<RichText>|null
     */
    #[Description('')]
    protected ?array $caption = null;
    #[Description('')]
    protected ?string $url = null;
    /**
     * @param array<RichText>|null $caption
     */
    public function setCaption(?array $caption): void
    {
        $this->caption = $caption;
    }
    /**
     * @return array<RichText>|null
     */
    public function getCaption(): ?array
    {
        return $this->caption;
    }
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }
    public function getUrl(): ?string
    {
        return $this->url;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('caption', $this->caption);
        $record->put('url', $this->url);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
