<?php
/**
 * BulletedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class BulletedListItem implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<BulletedListItem>|null
     */
    #[Key('rich_text')]
    #[Description('')]
    protected ?array $richText = null;
    #[Description('')]
    protected ?string $color = null;
    /**
     * @var array<Block>|null
     */
    #[Description('')]
    protected ?array $children = null;
    /**
     * @param array<BulletedListItem>|null $richText
     */
    public function setRichText(?array $richText): void
    {
        $this->richText = $richText;
    }
    /**
     * @return array<BulletedListItem>|null
     */
    public function getRichText(): ?array
    {
        return $this->richText;
    }
    public function setColor(?string $color): void
    {
        $this->color = $color;
    }
    public function getColor(): ?string
    {
        return $this->color;
    }
    /**
     * @param array<Block>|null $children
     */
    public function setChildren(?array $children): void
    {
        $this->children = $children;
    }
    /**
     * @return array<Block>|null
     */
    public function getChildren(): ?array
    {
        return $this->children;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('rich_text', $this->richText);
        $record->put('color', $this->color);
        $record->put('children', $this->children);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
