<?php
/**
 * Code automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class Code implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<RichText>|null
     */
    #[Description('')]
    protected ?array $caption = null;
    /**
     * @var array<RichText>|null
     */
    #[Key('rich_text')]
    #[Description('')]
    protected ?array $richText = null;
    #[Description('')]
    protected ?string $language = null;
    /**
     * @param array<RichText>|null $caption
     */
    public function setCaption(?array $caption): void
    {
        $this->caption = $caption;
    }
    /**
     * @return array<RichText>|null
     */
    public function getCaption(): ?array
    {
        return $this->caption;
    }
    /**
     * @param array<RichText>|null $richText
     */
    public function setRichText(?array $richText): void
    {
        $this->richText = $richText;
    }
    /**
     * @return array<RichText>|null
     */
    public function getRichText(): ?array
    {
        return $this->richText;
    }
    public function setLanguage(?string $language): void
    {
        $this->language = $language;
    }
    public function getLanguage(): ?string
    {
        return $this->language;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('caption', $this->caption);
        $record->put('rich_text', $this->richText);
        $record->put('language', $this->language);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
