<?php
/**
 * Comment automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class Comment implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?PageId $parent = null;
    #[Key('discussion_id')]
    #[Description('')]
    protected ?string $discussionId = null;
    #[Key('rich_text')]
    #[Description('')]
    protected ?RichText $richText = null;
    public function setParent(?PageId $parent) : void
    {
        $this->parent = $parent;
    }
    public function getParent() : ?PageId
    {
        return $this->parent;
    }
    public function setDiscussionId(?string $discussionId) : void
    {
        $this->discussionId = $discussionId;
    }
    public function getDiscussionId() : ?string
    {
        return $this->discussionId;
    }
    public function setRichText(?RichText $richText) : void
    {
        $this->richText = $richText;
    }
    public function getRichText() : ?RichText
    {
        return $this->richText;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('parent', $this->parent);
        $record->put('discussion_id', $this->discussionId);
        $record->put('rich_text', $this->richText);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
