<?php
/**
 * DatabaseParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class DatabaseParentId extends ParentId implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('database_id')]
    #[Description('')]
    protected ?string $databaseId = null;
    public function setDatabaseId(?string $databaseId): void
    {
        $this->databaseId = $databaseId;
    }
    public function getDatabaseId(): ?string
    {
        return $this->databaseId;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('database_id', $this->databaseId);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
