<?php
/**
 * EmojiIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class EmojiIcon extends Icon implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $emoji = null;
    public function setEmoji(?string $emoji): void
    {
        $this->emoji = $emoji;
    }
    public function getEmoji(): ?string
    {
        return $this->emoji;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('emoji', $this->emoji);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
