<?php
/**
 * ExternalIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ExternalIcon extends Icon implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?External $external = null;
    public function setExternal(?External $external): void
    {
        $this->external = $external;
    }
    public function getExternal(): ?External
    {
        return $this->external;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('external', $this->external);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
