<?php
/**
 * FileIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class FileIcon extends Icon implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?FileObject $file = null;
    public function setFile(?FileObject $file): void
    {
        $this->file = $file;
    }
    public function getFile(): ?FileObject
    {
        return $this->file;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('file', $this->file);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
