<?php
/**
 * PDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\DerivedType;
use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Discriminator;

#[Description('')]
#[Discriminator('type')]
#[DerivedType(PDFExternal::class, 'external')]
#[DerivedType(PDFFile::class, 'file')]
abstract class PDF implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<RichText>|null
     */
    #[Description('')]
    protected ?array $caption = null;
    #[Description('')]
    protected ?string $type = null;
    /**
     * @param array<RichText>|null $caption
     */
    public function setCaption(?array $caption): void
    {
        $this->caption = $caption;
    }
    /**
     * @return array<RichText>|null
     */
    public function getCaption(): ?array
    {
        return $this->caption;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('caption', $this->caption);
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
