<?php
/**
 * RichTextText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class RichTextText extends RichText implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?Text $text = null;
    public function setText(?Text $text): void
    {
        $this->text = $text;
    }
    public function getText(): ?Text
    {
        return $this->text;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('text', $this->text);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
