<?php
/**
 * UserCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class UserCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<User>|null
     */
    #[Description('')]
    protected ?array $results = null;
    #[Key('next_cursor')]
    #[Description('')]
    protected ?string $nextCursor = null;
    #[Key('has_more')]
    #[Description('')]
    protected ?bool $hasMore = null;
    /**
     * @param array<User>|null $results
     */
    public function setResults(?array $results) : void
    {
        $this->results = $results;
    }
    /**
     * @return array<User>|null
     */
    public function getResults() : ?array
    {
        return $this->results;
    }
    public function setNextCursor(?string $nextCursor) : void
    {
        $this->nextCursor = $nextCursor;
    }
    public function getNextCursor() : ?string
    {
        return $this->nextCursor;
    }
    public function setHasMore(?bool $hasMore) : void
    {
        $this->hasMore = $hasMore;
    }
    public function getHasMore() : ?bool
    {
        return $this->hasMore;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('results', $this->results);
        $record->put('next_cursor', $this->nextCursor);
        $record->put('has_more', $this->hasMore);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
