<?php
/**
 * User automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class User implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $object = null;
    #[Description('')]
    protected ?string $id = null;
    #[Description('')]
    protected ?string $type = null;
    #[Description('')]
    protected ?Person $person = null;
    #[Description('')]
    protected ?string $name = null;
    #[Key('avatar_url')]
    #[Description('')]
    protected ?string $avatarUrl = null;
    public function setObject(?string $object) : void
    {
        $this->object = $object;
    }
    public function getObject() : ?string
    {
        return $this->object;
    }
    public function setId(?string $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?string
    {
        return $this->id;
    }
    public function setType(?string $type) : void
    {
        $this->type = $type;
    }
    public function getType() : ?string
    {
        return $this->type;
    }
    public function setPerson(?Person $person) : void
    {
        $this->person = $person;
    }
    public function getPerson() : ?Person
    {
        return $this->person;
    }
    public function setName(?string $name) : void
    {
        $this->name = $name;
    }
    public function getName() : ?string
    {
        return $this->name;
    }
    public function setAvatarUrl(?string $avatarUrl) : void
    {
        $this->avatarUrl = $avatarUrl;
    }
    public function getAvatarUrl() : ?string
    {
        return $this->avatarUrl;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('object', $this->object);
        $record->put('id', $this->id);
        $record->put('type', $this->type);
        $record->put('person', $this->person);
        $record->put('name', $this->name);
        $record->put('avatar_url', $this->avatarUrl);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
