<?php
/**
 * WorkspaceParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Notion;

use PSX\Schema\Attribute\Description;

#[Description('')]
class WorkspaceParentId extends ParentId implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?bool $workspace = null;
    public function setWorkspace(?bool $workspace): void
    {
        $this->workspace = $workspace;
    }
    public function getWorkspace(): ?bool
    {
        return $this->workspace;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('workspace', $this->workspace);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
